import { CalendarDays, ChevronRight, Clock3, Copy, ExternalLink, FileText, Globe2, ListFilter, Pencil, Plus, RotateCcw, Save, Trash2, Undo2, UserRound } from "lucide-react";
import { useCallback, useEffect, useMemo, useRef, useState, type ReactNode } from "react";

import type { AppointmentTypeDateOverride, BookingTimeRange, PublicAppointmentType, PublicBookingProfile, SaveBookingSettingsInput, ScheduleOverviewResponse } from "../../shared/types";
import { PageHeader } from "../components/common/page-header";
import { ErrorState } from "../components/states/error-state";
import { LoadingState } from "../components/states/loading-state";
import { Badge } from "../components/ui/badge";
import { Button } from "../components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "../components/ui/card";
import { Checkbox } from "../components/ui/checkbox";
import { Input } from "../components/ui/input";
import { Select } from "../components/ui/select";
import { Textarea } from "../components/ui/textarea";
import { api, getDisplayErrorMessage, isApiConfigured } from "../lib/api";

type BookingSettingsResponse = { profile: PublicBookingProfile | null };
type Day = keyof NonNullable<PublicAppointmentType["weeklyAvailability"]>;
const days: Array<{ key: Day; label: string }> = [
  { key: "monday", label: "Monday" }, { key: "tuesday", label: "Tuesday" }, { key: "wednesday", label: "Wednesday" }, { key: "thursday", label: "Thursday" }, { key: "friday", label: "Friday" }, { key: "saturday", label: "Saturday" }, { key: "sunday", label: "Sunday" },
];
const timeOptions = Array.from({ length: 96 }, (_, index) => `${String(Math.floor(index / 4)).padStart(2, "0")}:${String((index % 4) * 15).padStart(2, "0")}`);
const durationOptions = [15, 30, 45, 60, 90, 120];
const timezoneOptions = ["America/St_Johns", "America/Halifax", "America/Toronto", "America/Winnipeg", "America/Regina", "America/Edmonton", "America/Vancouver", "America/Whitehorse", "America/Dawson", "UTC"];
const defaultDraft = (): SaveBookingSettingsInput => ({ enabled: false, slug: "", displayName: "", introduction: "", timezone: Intl.DateTimeFormat().resolvedOptions().timeZone || "America/Toronto", startIntervalMinutes: 30, bookingCalendarId: "", conflictCalendarIds: [], minimumNoticeMinutes: 60, maximumBookingDays: 90, globalDateOverrides: [], appointmentTypes: [] });
const profileToDraft = (profile: PublicBookingProfile | null): SaveBookingSettingsInput => profile ? ({ enabled: profile.enabled, slug: profile.slug, displayName: profile.displayName, introduction: profile.introduction ?? "", timezone: profile.timezone, startIntervalMinutes: profile.startIntervalMinutes, bookingCalendarId: profile.bookingCalendarId ?? "", conflictCalendarIds: profile.conflictCalendarIds, minimumNoticeMinutes: profile.minimumNoticeMinutes, maximumBookingDays: profile.maximumBookingDays, globalDateOverrides: profile.globalDateOverrides, appointmentTypes: profile.appointmentTypes }) : defaultDraft();
const newAppointmentType = (): PublicAppointmentType => ({ id: globalThis.crypto?.randomUUID?.() ?? `appointment-${Date.now()}`, name: "New appointment", enabled: true, allowedDurationsMinutes: [30], defaultDurationMinutes: 30, weeklyAvailability: {}, dateOverrides: [] });
const setRanges = (type: PublicAppointmentType, day: Day, ranges: BookingTimeRange[]): PublicAppointmentType => ({ ...type, weeklyAvailability: { ...type.weeklyAvailability, ...(ranges.length ? { [day]: ranges } : { [day]: undefined }) } });
const formatDuration = (duration: number) => ({ 15: "15 min", 30: "30 min", 45: "45 min", 60: "1 hr", 90: "1.5 hr", 120: "2 hrs" })[duration] ?? `${duration} min`;
const availabilitySummary = (type: PublicAppointmentType) => days.filter(({ key }) => type.weeklyAvailability[key]?.length).map(({ label }) => label.slice(0, 3)).join(", ") || "No availability";
const makeSlugSuffix = () => Array.from(globalThis.crypto.getRandomValues(new Uint8Array(4)), (byte) => byte.toString(16).padStart(2, "0")).join("");
const generatePublicSlug = (displayName: string, suffix: string) => {
  if (!displayName.trim()) return "";
  const namePart = displayName.normalize("NFKD").replace(/[\u0300-\u036f]/g, "").toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-+|-+$/g, "").slice(0, 55).replace(/-+$/g, "");
  return `${namePart || "booking"}-${suffix}`;
};

export const BookingSettingsPage = () => {
  const [draft, setDraft] = useState<SaveBookingSettingsInput>(defaultDraft);
  const [saved, setSaved] = useState<SaveBookingSettingsInput>(defaultDraft);
  const [overview, setOverview] = useState<ScheduleOverviewResponse | null>(null);
  const [selectedTypeId, setSelectedTypeId] = useState<string | null>(null);
  const slugSuffix = useRef<string | null>(null);
  const [loading, setLoading] = useState(true);
  const [saving, setSaving] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [notice, setNotice] = useState<string | null>(null);

  const load = useCallback(async () => {
    setLoading(true); setError(null);
    try {
      const [settings, schedule] = await Promise.all([api.get<BookingSettingsResponse>("/booking-settings"), api.get<ScheduleOverviewResponse>("/schedule/overview")]);
      const next = profileToDraft(settings.profile); slugSuffix.current = null; setDraft(next); setSaved(next); setOverview(schedule); setSelectedTypeId(next.appointmentTypes[0]?.id ?? null);
    } catch (reason) { setError(getDisplayErrorMessage(reason, "Unable to load public booking settings.")); }
    finally { setLoading(false); }
  }, []);
  useEffect(() => { void load(); }, [load]);

  const calendars = overview?.calendars ?? [];
  const publicUrl = useMemo(() => draft.slug.trim() ? `${window.location.origin}/book/${draft.slug.trim().toLowerCase()}` : "", [draft.slug]);
  const slugResetPending = Boolean(saved.slug && draft.slug !== saved.slug);
  const linkIsSaved = Boolean(saved.slug && draft.slug === saved.slug);
  const enabledTypes = draft.appointmentTypes.filter((type) => type.enabled);
  const canEnable = Boolean(draft.displayName.trim() && /^[a-z0-9-]{3,64}$/.test(draft.slug.trim().toLowerCase()) && draft.timezone.trim() && overview?.connection && draft.bookingCalendarId && enabledTypes.length && enabledTypes.some((type) => Object.values(type.weeklyAvailability).some((ranges) => ranges?.length)));
  const selectedType = draft.appointmentTypes.find((type) => type.id === selectedTypeId) ?? draft.appointmentTypes[0];
  const updateType = (id: string, update: (type: PublicAppointmentType) => PublicAppointmentType) => setDraft((current) => ({ ...current, appointmentTypes: current.appointmentTypes.map((type) => type.id === id ? update(type) : type) }));
  const updateDisplayName = (displayName: string) => {
    if (saved.slug && !slugSuffix.current) { setDraft((current) => ({ ...current, displayName })); return; }
    slugSuffix.current ??= makeSlugSuffix();
    setDraft((current) => ({ ...current, displayName, slug: generatePublicSlug(displayName, slugSuffix.current ?? "") }));
  };
  const resetSlug = () => {
    if (!draft.displayName.trim()) return;
    let suffix = makeSlugSuffix();
    while (generatePublicSlug(draft.displayName, suffix) === draft.slug) suffix = makeSlugSuffix();
    slugSuffix.current = suffix;
    setDraft((current) => ({ ...current, slug: generatePublicSlug(current.displayName, suffix) }));
  };
  const undoSlugReset = () => {
    slugSuffix.current = null;
    setDraft((current) => ({ ...current, slug: saved.slug }));
  };
  const addType = () => { const type = newAppointmentType(); setDraft((current) => ({ ...current, appointmentTypes: [...current.appointmentTypes, type] })); setSelectedTypeId(type.id); };
  const deleteType = (id: string) => setDraft((current) => { const appointmentTypes = current.appointmentTypes.filter((type) => type.id !== id); setSelectedTypeId(appointmentTypes[0]?.id ?? null); return { ...current, appointmentTypes }; });
  const save = async () => { setSaving(true); setError(null); setNotice(null); try { const response = await api.put<BookingSettingsResponse>("/booking-settings", { ...draft, slug: draft.slug.trim().toLowerCase() }); const next = profileToDraft(response.profile); slugSuffix.current = null; setDraft(next); setSaved(next); setNotice("Public booking settings saved."); } catch (reason) { setError(getDisplayErrorMessage(reason, "Unable to save public booking settings.")); } finally { setSaving(false); } };
  const copyLink = async () => { try { await navigator.clipboard.writeText(publicUrl); setNotice("Public link copied."); } catch { setError("Unable to copy the link. Please copy it manually."); } };

  if (!isApiConfigured) return <ErrorState title="API not configured" description="Set `VITE_API_BASE_URL` or regenerate `amplify_outputs.json` before configuring public booking." />;
  if (loading) return <LoadingState title="Preparing public booking settings" description="Loading your profile and Google Calendar configuration." />;
  if (!overview) return <ErrorState title="Unable to load public booking settings" description={error ?? "Try again."} action={<Button onClick={() => void load()} type="button">Retry</Button>} />;

  return <div className="space-y-5">
    <PageHeader title="Public Booking" description="Configure your public page, calendar rules, and appointment types."><div className="flex flex-wrap items-center gap-2"><Badge variant={draft.enabled ? "success" : "neutral"}>{draft.enabled ? "Public booking enabled" : "Not enabled"}</Badge><Button disabled={saving || JSON.stringify(draft) === JSON.stringify(saved)} onClick={() => void save()} type="button"><Save className="h-4 w-4" />{saving ? "Saving..." : "Save settings"}</Button></div></PageHeader>
    {error ? <ErrorState title="Booking settings action failed" description={error} /> : null}{notice ? <div className="rounded-md border border-emerald-200 bg-emerald-50 p-3 text-sm text-emerald-900">{notice}</div> : null}
    <div className="grid gap-4 xl:grid-cols-[1.35fr_1fr]">
      <Card><CardHeader><SectionHeading icon={<Globe2 />} title="Public page settings" description="Control your public booking page and how it appears to visitors." /></CardHeader><CardContent className="space-y-4"><label className="flex items-center gap-3"><Checkbox checked={draft.enabled} disabled={!draft.enabled && !canEnable} onChange={(event) => setDraft({ ...draft, enabled: event.target.checked })} /><span><span className="block text-sm font-semibold">Enable public booking</span><span className="text-xs text-muted-foreground">{canEnable ? "Your booking page is ready to accept appointments." : "Complete the required calendar and appointment type settings first."}</span></span></label><label className="block space-y-1"><span className="text-sm font-medium">Public display name</span><Input value={draft.displayName} onChange={(e) => updateDisplayName(e.target.value)} /></label><div className="grid gap-3 md:grid-cols-[minmax(10rem,.5fr)_minmax(16rem,1.5fr)]"><div className="space-y-1"><label className="block space-y-1"><span className="text-sm font-medium">Public slug</span><Input readOnly value={draft.slug} placeholder="Generated from your display name" /></label><div className="flex flex-wrap items-center gap-2"><Button disabled={!draft.displayName.trim() || saving} onClick={resetSlug} size="sm" type="button" variant="outline"><RotateCcw className="h-3.5 w-3.5" />Reset slug</Button>{slugResetPending ? <Button onClick={undoSlugReset} size="sm" type="button" variant="ghost"><Undo2 className="h-3.5 w-3.5" />Undo</Button> : null}</div></div><div className="space-y-1"><span className="text-sm font-medium">Generated public URL</span><div className="flex flex-wrap gap-2"><Input className="min-w-0 flex-1" readOnly value={publicUrl} placeholder="Enter a display name to generate a URL" /><Button disabled={!linkIsSaved} onClick={() => void copyLink()} type="button" variant="outline"><Copy className="h-4 w-4" />Copy link</Button><Button disabled={!linkIsSaved} onClick={() => window.open(publicUrl, "_blank", "noopener,noreferrer")} type="button" variant="outline"><ExternalLink className="h-4 w-4" />Open</Button></div></div></div>{slugResetPending ? <p className="text-xs text-amber-700">Save settings to activate the new link. The old public link will stop working after you save.</p> : !saved.slug && draft.slug ? <p className="text-xs text-muted-foreground">Save settings before sharing or opening this link.</p> : null}</CardContent></Card>
      <Card><CardHeader><SectionHeading icon={<ListFilter />} title="Booking rules" description="Set the general rules for how appointments can be booked." /></CardHeader><CardContent className="grid gap-4 sm:grid-cols-2"><label className="block space-y-1"><span className="text-sm font-medium">Timezone</span><Select value={draft.timezone} onChange={(e) => setDraft({ ...draft, timezone: e.target.value })}>{!timezoneOptions.includes(draft.timezone) ? <option value={draft.timezone}>{draft.timezone}</option> : null}{timezoneOptions.map((timezone) => <option key={timezone} value={timezone}>{timezone}</option>)}</Select></label><label className="block space-y-1"><span className="text-sm font-medium">Start-time interval</span><Select value={draft.startIntervalMinutes} onChange={(e) => setDraft({ ...draft, startIntervalMinutes: Number(e.target.value) as 15 | 30 })}><option value={15}>15 minutes</option><option value={30}>30 minutes</option></Select><span className="block text-xs text-muted-foreground">This controls how often an appointment may start. It does not control appointment duration.</span></label><label className="block space-y-1"><span className="text-sm font-medium">Minimum booking notice</span><Input min={0} type="number" value={draft.minimumNoticeMinutes} onChange={(e) => setDraft({ ...draft, minimumNoticeMinutes: Number(e.target.value) })} /><span className="text-xs text-muted-foreground">minutes</span></label><label className="block space-y-1"><span className="text-sm font-medium">Maximum future booking days</span><Input min={1} type="number" value={draft.maximumBookingDays} onChange={(e) => setDraft({ ...draft, maximumBookingDays: Number(e.target.value) })} /><span className="text-xs text-muted-foreground">days</span></label></CardContent></Card>
    </div>
    <Card><CardHeader><SectionHeading icon={<FileText />} title="Introduction message" description="This message will be shown at the top of your public booking page." /></CardHeader><CardContent><Textarea className="min-h-24" value={draft.introduction ?? ""} onChange={(e) => setDraft({ ...draft, introduction: e.target.value })} /></CardContent></Card>
    <Card><CardHeader><SectionHeading icon={<CalendarDays />} title="Calendars" description="Select your booking calendar and any calendars to check for conflicts." /><Badge variant={overview.connection ? "success" : "warning"}>{overview.connection ? "Google connected" : "Connect Google first"}</Badge></CardHeader><CardContent className="space-y-4"><label className="block space-y-1"><span className="text-sm font-medium">Booking calendar</span><Select disabled={!overview.connection} value={draft.bookingCalendarId ?? ""} onChange={(e) => setDraft({ ...draft, bookingCalendarId: e.target.value })}><option value="">Select a writable calendar</option>{calendars.filter((calendar) => calendar.accessRole === "owner" || calendar.accessRole === "writer").map((calendar) => <option key={calendar.calendarId} value={calendar.calendarId}>{calendar.summary}</option>)}</Select><span className="text-xs text-muted-foreground">Only calendars from your connected Google account can be selected.</span></label><fieldset className="space-y-2"><legend className="text-sm font-medium">Conflict calendars</legend><div className="flex flex-wrap gap-2">{calendars.map((calendar) => <label className="flex items-center gap-2 rounded-full border border-border bg-slate-50 px-3 py-2 text-sm" key={calendar.calendarId}><Checkbox checked={draft.conflictCalendarIds.includes(calendar.calendarId)} onChange={(e) => setDraft({ ...draft, conflictCalendarIds: e.target.checked ? [...draft.conflictCalendarIds, calendar.calendarId] : draft.conflictCalendarIds.filter((id) => id !== calendar.calendarId) })} />{calendar.summary}</label>)}{!calendars.length ? <span className="text-xs text-muted-foreground">Refresh your Google calendar list in Connect & Configure.</span> : null}</div><p className="text-xs text-muted-foreground">Selected calendars will be checked for conflicts when showing availability.</p></fieldset></CardContent></Card>
    <div className="grid gap-4 xl:grid-cols-[minmax(18rem,.7fr)_minmax(0,1.3fr)]">
      <Card className="self-start"><CardHeader className="border-b border-border/70"><div><CardTitle className="text-base">Appointment types</CardTitle><CardDescription>Create and manage the types of appointments people can book.</CardDescription></div></CardHeader><CardContent className="space-y-3 pt-3"><Button className="w-full" onClick={addType} type="button"><Plus className="h-4 w-4" />Add appointment type</Button><div className="space-y-2">{draft.appointmentTypes.map((type) => <button className={`w-full rounded-md border p-3 text-left transition-colors ${selectedType?.id === type.id ? "border-primary bg-primary/5 ring-1 ring-primary/20" : "border-border bg-card hover:bg-slate-50"}`} key={type.id} onClick={() => setSelectedTypeId(type.id)} type="button"><div className="flex gap-3"><div className="flex h-9 w-9 shrink-0 items-center justify-center rounded-md bg-primary/10 text-primary"><UserRound className="h-5 w-5" /></div><div className="min-w-0 flex-1"><div className="flex items-center justify-between gap-2"><span className="truncate text-sm font-semibold">{type.name || "Untitled appointment"}</span><ChevronRight className="h-4 w-4 text-primary" /></div><p className={`mt-1 text-xs font-medium ${type.enabled ? "text-emerald-700" : "text-muted-foreground"}`}>{type.enabled ? "● Enabled" : "○ Disabled"}</p><p className="mt-1 flex items-center gap-1 text-xs text-muted-foreground"><CalendarDays className="h-3.5 w-3.5" />{type.allowedDurationsMinutes.includes(type.defaultDurationMinutes) ? `${formatDuration(type.defaultDurationMinutes)} (default)` : "Choose default duration"}</p><p className="mt-1 flex items-center gap-1 text-xs text-muted-foreground"><Clock3 className="h-3.5 w-3.5" />{availabilitySummary(type)}</p></div></div></button>)}{!draft.appointmentTypes.length ? <p className="rounded-md border border-dashed border-border p-4 text-sm text-muted-foreground">Add an appointment type such as Confession or Phone Call.</p> : null}</div></CardContent></Card>
      <Card>{selectedType ? <AppointmentTypeEditor type={selectedType} onChange={(next) => updateType(selectedType.id, () => next)} onDelete={() => deleteType(selectedType.id)} /> : <CardContent className="py-12 text-center text-sm text-muted-foreground">Add an appointment type to configure its public availability.</CardContent>}</Card>
    </div>
    <Card><CardHeader><SectionHeading icon={<CalendarDays />} title="Blackout dates" description="These dates make every appointment type unavailable. Add dates for vacation, retreat, travel, or parish events." /><Button onClick={() => setDraft({ ...draft, globalDateOverrides: [...draft.globalDateOverrides, { date: "", unavailable: true }] })} type="button"><Plus className="h-4 w-4" />Add blackout</Button></CardHeader><CardContent className="space-y-3"><div className="flex flex-wrap gap-2"><Badge variant="neutral">All types</Badge>{draft.appointmentTypes.map((type) => <span className="rounded-full border border-border px-3 py-1 text-xs text-muted-foreground" key={type.id}>{type.name || "Untitled type"}</span>)}</div><div className="space-y-2">{draft.globalDateOverrides.map((override, index) => <div className="flex flex-wrap items-center gap-3 rounded-md border border-border bg-card p-3" key={`${override.date}-${index}`}><CalendarDays className="h-5 w-5 text-primary" /><Input className="w-44" type="date" value={override.date} onChange={(e) => setDraft({ ...draft, globalDateOverrides: draft.globalDateOverrides.map((item, itemIndex) => itemIndex === index ? { ...item, date: e.target.value } : item) })} /><Badge variant="warning">Unavailable for all types</Badge><span className="min-w-28 flex-1 text-sm text-muted-foreground">Public booking blackout</span><Button aria-label="Remove blackout date" onClick={() => setDraft({ ...draft, globalDateOverrides: draft.globalDateOverrides.filter((_, itemIndex) => itemIndex !== index) })} size="icon" type="button" variant="ghost"><Trash2 className="h-4 w-4" /></Button></div>)}{!draft.globalDateOverrides.length ? <p className="rounded-md border border-dashed border-border p-4 text-sm text-muted-foreground">No priest-wide blackout dates.</p> : null}</div></CardContent></Card>
  </div>;
};

const SectionHeading = ({ icon, title, description }: { icon: ReactNode; title: string; description: string }) => <div className="flex gap-3"><span className="mt-0.5 text-primary [&>svg]:h-6 [&>svg]:w-6">{icon}</span><div><CardTitle className="text-base">{title}</CardTitle><CardDescription>{description}</CardDescription></div></div>;

const AppointmentTypeEditor = ({ type, onChange, onDelete }: { type: PublicAppointmentType; onChange: (type: PublicAppointmentType) => void; onDelete: () => void }) => {
  const update = (patch: Partial<PublicAppointmentType>) => onChange({ ...type, ...patch });
  const toggleDuration = (duration: number, checked: boolean) => { const allowed = checked ? [...type.allowedDurationsMinutes, duration].sort((a, b) => a - b) : type.allowedDurationsMinutes.filter((value) => value !== duration); update({ allowedDurationsMinutes: allowed, defaultDurationMinutes: allowed.includes(type.defaultDurationMinutes) ? type.defaultDurationMinutes : (allowed[0] ?? 0) }); };
  return <><CardHeader className="border-b border-border/70"><div><CardTitle className="text-lg">{type.name || "Untitled appointment"}</CardTitle><CardDescription>Edit the details, availability, and settings for this appointment type.</CardDescription></div><Button className="text-rose-600 hover:text-rose-700" onClick={onDelete} type="button" variant="ghost"><Trash2 className="h-4 w-4" />Delete</Button></CardHeader><CardContent className="space-y-5 pt-4"><label className="flex items-center gap-3"><Checkbox checked={type.enabled} onChange={(e) => update({ enabled: e.target.checked })} /><span><span className="block text-sm font-semibold">Enabled</span><span className="text-xs text-muted-foreground">This appointment type is available for public booking.</span></span></label><div className="grid gap-3 md:grid-cols-3"><label className="space-y-1"><span className="text-sm font-medium">Name</span><Input value={type.name} onChange={(e) => update({ name: e.target.value })} /></label><label className="space-y-1"><span className="text-sm font-medium">Public location</span><Input value={type.publicLocation ?? ""} onChange={(e) => update({ publicLocation: e.target.value })} /></label><label className="space-y-1"><span className="text-sm font-medium">Default duration</span><Select disabled={!type.allowedDurationsMinutes.length} value={type.allowedDurationsMinutes.includes(type.defaultDurationMinutes) ? type.defaultDurationMinutes : ""} onChange={(e) => update({ defaultDurationMinutes: Number(e.target.value) })}><option value="">Choose duration</option>{type.allowedDurationsMinutes.map((duration) => <option key={duration} value={duration}>{formatDuration(duration)}</option>)}</Select></label><label className="space-y-1 md:col-span-3"><span className="text-sm font-medium">Description</span><Textarea value={type.description ?? ""} onChange={(e) => update({ description: e.target.value })} /></label></div><fieldset><legend className="mb-2 text-sm font-medium">Allowed durations</legend><div className="flex flex-wrap gap-x-4 gap-y-2">{durationOptions.map((duration) => <label className="flex items-center gap-1.5 text-sm" key={duration}><Checkbox checked={type.allowedDurationsMinutes.includes(duration)} onChange={(e) => toggleDuration(duration, e.target.checked)} />{formatDuration(duration)}</label>)}</div>{!type.allowedDurationsMinutes.length ? <p className="mt-1 text-xs text-amber-700">Select at least one duration, then choose a default.</p> : null}</fieldset><AvailabilityEditor type={type} onChange={onChange} /><DateOverrideEditor type={type} onChange={onChange} /></CardContent></>;
};

const AvailabilityEditor = ({ type, onChange }: { type: PublicAppointmentType; onChange: (type: PublicAppointmentType) => void }) => {
  const [editing, setEditing] = useState<{ day: Day; index: number | null; start: string; end: string } | null>(null);
  const beginAdd = (day: Day) => setEditing({ day, index: null, start: "09:00", end: "17:00" });
  const saveRange = () => {
    if (!editing) return;
    const ranges = type.weeklyAvailability[editing.day] ?? [];
    const next = editing.index === null ? [...ranges, { start: editing.start, end: editing.end }] : ranges.map((range, index) => index === editing.index ? { start: editing.start, end: editing.end } : range);
    onChange(setRanges(type, editing.day, next)); setEditing(null);
  };
  return <div className="space-y-2"><div><h3 className="text-sm font-medium">Weekly availability</h3><p className="text-xs text-muted-foreground">Set the days and times when this appointment type can be booked. Times use 15-minute increments.</p></div><div className="overflow-hidden rounded-md border border-border">{days.map(({ key, label }) => {
    const ranges = type.weeklyAvailability[key] ?? [];
    const apply = (next: BookingTimeRange[]) => onChange(setRanges(type, key, next));
    const isEditingDay = editing?.day === key;
    return <div className="border-b border-border last:border-b-0" key={key}><div className="flex items-center gap-2 px-3 py-2"><span className="w-28 shrink-0 text-sm font-medium">{label}</span><div className="flex min-w-0 flex-1 flex-wrap gap-2">{ranges.map((range, index) => <div className="flex items-center gap-1 rounded bg-slate-50 px-2 py-1 text-sm text-muted-foreground" key={`${range.start}-${index}`}><span>{range.start} – {range.end}</span><Button aria-label={`Edit ${label} period`} onClick={() => setEditing({ day: key, index, start: range.start, end: range.end })} size="icon" type="button" variant="ghost"><Pencil className="h-3.5 w-3.5" /></Button><Button aria-label={`Remove ${label} period`} onClick={() => apply(ranges.filter((_, itemIndex) => itemIndex !== index))} size="icon" type="button" variant="ghost"><Trash2 className="h-3.5 w-3.5" /></Button></div>)}{!ranges.length && !isEditingDay ? <span className="py-1 text-sm text-muted-foreground">Unavailable</span> : null}</div>{!isEditingDay ? <Button onClick={() => beginAdd(key)} size="sm" type="button" variant="outline"><Plus className="h-3.5 w-3.5" />Add</Button> : null}</div>{isEditingDay && editing ? <div className="flex flex-wrap items-center gap-2 border-t border-border bg-slate-50 px-3 py-2"><span className="w-28 text-xs text-muted-foreground">{editing.index === null ? "New period" : "Edit period"}</span><Select className="w-28" value={editing.start} onChange={(e) => setEditing({ ...editing, start: e.target.value })}>{timeOptions.map((time) => <option key={time}>{time}</option>)}</Select><span className="text-xs">to</span><Select className="w-28" value={editing.end} onChange={(e) => setEditing({ ...editing, end: e.target.value })}>{timeOptions.map((time) => <option key={time}>{time}</option>)}</Select><Button onClick={saveRange} size="sm" type="button">{editing.index === null ? "Add period" : "Save"}</Button><Button onClick={() => setEditing(null)} size="sm" type="button" variant="ghost">Cancel</Button></div> : null}</div>;
  })}</div></div>;
};

const DateOverrideEditor = ({ type, onChange }: { type: PublicAppointmentType; onChange: (type: PublicAppointmentType) => void }) => {
  const update = (overrides: AppointmentTypeDateOverride[]) => onChange({ ...type, dateOverrides: overrides });
  return <div className="space-y-2"><div className="flex items-center justify-between"><div><h3 className="text-sm font-medium">Date overrides</h3><p className="text-xs text-muted-foreground">Changes only this appointment type’s normal weekly availability.</p></div><Button onClick={() => update([...type.dateOverrides, { date: "", unavailable: true }])} size="sm" type="button" variant="outline"><Plus className="h-3.5 w-3.5" />Add exception</Button></div>{type.dateOverrides.map((override, index) => <div className="flex flex-wrap items-center gap-2 rounded-md border border-border bg-slate-50 p-2" key={`${override.date}-${index}`}><Input className="w-40" type="date" value={override.date} onChange={(e) => update(type.dateOverrides.map((item, itemIndex) => itemIndex === index ? { ...item, date: e.target.value } : item))} /><Select className="w-40" value={"unavailable" in override ? "unavailable" : "hours"} onChange={(e) => update(type.dateOverrides.map((item, itemIndex) => itemIndex !== index ? item : e.target.value === "unavailable" ? { date: item.date, unavailable: true } : { date: item.date, ranges: [{ start: "09:00", end: "17:00" }] }))}><option value="unavailable">Unavailable</option><option value="hours">Replacement hours</option></Select>{"ranges" in override ? <><Select className="w-28" value={override.ranges[0]?.start ?? "09:00"} onChange={(e) => update(type.dateOverrides.map((item, itemIndex) => itemIndex === index && "ranges" in item ? { ...item, ranges: [{ ...(item.ranges[0] ?? { end: "17:00" }), start: e.target.value }] } : item))}>{timeOptions.map((time) => <option key={time}>{time}</option>)}</Select><span className="text-xs">to</span><Select className="w-28" value={override.ranges[0]?.end ?? "17:00"} onChange={(e) => update(type.dateOverrides.map((item, itemIndex) => itemIndex === index && "ranges" in item ? { ...item, ranges: [{ ...(item.ranges[0] ?? { start: "09:00" }), end: e.target.value }] } : item))}>{timeOptions.map((time) => <option key={time}>{time}</option>)}</Select></> : null}<Button aria-label="Remove date override" onClick={() => update(type.dateOverrides.filter((_, itemIndex) => itemIndex !== index))} size="icon" type="button" variant="ghost"><Trash2 className="h-4 w-4" /></Button></div>)}{!type.dateOverrides.length ? <p className="rounded-md border border-dashed border-border p-4 text-sm text-muted-foreground">No date-specific exceptions.</p> : null}</div>;
};
